name: Email Notifications

on:
  push:
    branches:
      - master
    paths:
      - '_posts/**'  # This pattern watches for changes in the _posts folder and its subdirectories

jobs:
  send-email:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Set up Client Secrets
        run: echo "${{ secrets.CLIENT_SECRETS_JSON }}" > client_secrets.json

      - name: Send Email Notification
        run: |
          python send-email.py